### ISSUE TITLE
Sentiment Analysis for Text

### ISSUE THREAD

**Issue by prodigyinfotech** [Prodigy-InfoTech/Machine-Learning-Projects#11]
Develop a sentiment analysis model that can classify text as positive, negative, or neutral. You can start with movie reviews or social media comments datasets.

**Comment by ishan-nahid** [comment]
assign it to me.

**Comment by Rc17git** [comment]
Hi, I have created a pull request solving this issue.

**Comment by prodigyinfotech** [comment]
Hey @ishan-nahid,
Are you completing this Project?

**Comment by Rc17git** [comment]
Hi! @prodigyinfotech,
I am also working on issue #13 can you assign it to me? I am almost done with it and I will create a PR in an hour.

**Comment by prodigyinfotech** [comment]
> Hi! @prodigyinfotech, I am also working on issue #13 can you assign it to me? I am almost done with it and I will create a PR in an hour.

Please comment on the issue #13 to get it assigned to you

**Comment by ishan-nahid** [comment]
as someone else has done it two days ago, then i left the work. 
though i was working with bengali text sentiment analysis. 

is there any necessity of continuing my work?
i have seen his code and that is good enough. somewhere better then me.

**Comment by Rc17git** [comment]
> > Hi! @prodigyinfotech, I am also working on issue #13 can you assign it to me? I am almost done with it and I will create a PR in an hour.
> 
> Please comment on the issue #13 to get it assigned to you

Sure! I have commented on issue #13

**Comment by Rc17git** [comment]
Hi @prodigyinfotech , can you assign this task to me?
