### ISSUE TITLE
Handwritten Digit Recognition

### ISSUE THREAD

**Issue by prodigyinfotech** [Prodigy-InfoTech/Machine-Learning-Projects#14]
Implement a digit recognition system that can recognize handwritten digits (0-9). You can use the MNIST dataset for this project.

**Comment by ishan-nahid** [comment]
assign it to me.

**Comment by prodigyinfotech** [comment]
done

**Comment by ishan-nahid** [comment]
@prodigyinfotech  check, feedback and marge with "hacktoberfest-accepted" label.
