### ISSUE TITLE
Car Price Prediction

### ISSUE THREAD

**Issue by prodigyinfotech** [Prodigy-InfoTech/Machine-Learning-Projects#18]
Build a model to predict the price of used cars based on features like mileage, brand, year, and model.

**Comment by Dineshraju3435** [comment]
hi @prodigyinfotech ,so how exactly we should do this ?? and Is there any particular language to code or we can code in any language ??

**Comment by prodigyinfotech** [comment]
Hey @Dineshraju3435, 
You should be using python to build ML Models and use Jupyter Notebooks for ML Projects
