### ISSUE TITLE
HeartSync Pro : Heart Disease Recognition

### ISSUE THREAD

**Issue by Manavr472** [Prodigy-InfoTech/Machine-Learning-Projects#35]
### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Prodigy-InfoTech/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Nanzz94** [comment]
I can create this project. Please assign this to me. @Manavr472  @prodigyinfotech

**Comment by prodigyinfotech** [comment]
Done
