### ISSUE TITLE
Wine Quality Prediction

### ISSUE THREAD

**Issue by prodigyinfotech** [Prodigy-InfoTech/Machine-Learning-Projects#50]
Build a machine-learning model to predict the quality of wines by exploring their various chemical properties. Several factors other than age go into wine quality certification, which includes physiochemical tests like alcohol quantity, fixed acidity, volatile acidity, determination of density, pH, and more.

Dataset: [Link](https://raw.githubusercontent.com/amberkakkar01/Prediction-of-Wine-Quality/refs/heads/master/winequality-red.csv)

**Comment by rrayhka** [comment]
can u assign me under hacktoberfest?

**Comment by prodigyinfotech** [comment]
Done @rrayhka

**Comment by Nanzz94** [comment]
I can create this. Assign this task to me @prodigyinfotech

**Comment by rrayhka** [comment]
> I can create this. Assign this task to me @prodigyinfotech

bruh, i've done PR
