### ISSUE TITLE
Loan Eligibility Prediction

### ISSUE THREAD

**Issue by prodigyinfotech** [Prodigy-InfoTech/Machine-Learning-Projects#51]
Build a model for determining loan eligibility prediction has to be trained using a dataset that consists of data including data such as sex, marital status, number of dependents, income, qualifications, credit card history and loan amount to name a few.

**Comment by Afreen-Kazi-1** [comment]
Hello! Can you assign me this issue?
I'd like to contribute under Hacktoberfest 
I will be working on the dataset https://www.kaggle.com/datasets/devzohaib/eligibility-prediction-for-loan
