### ISSUE TITLE
Plant Species Identification

### ISSUE THREAD

**Issue by prodigyinfotech** [Prodigy-InfoTech/Machine-Learning-Projects#54]
Build a model that uses machine learning algorithms to correctly identify the plant species through the binary leaf images and evaluated features. These features include shape, margin, and texture.

**Comment by ahaandesai27** [comment]
Hello, I want to work on this.
Will use the dataset  https://www.kaggle.com/c/leaf-classification/data

**Comment by prodigyinfotech** [comment]
You can start working.

**Comment by ahaandesai27** [comment]
Could you also assign ayush-bothra , AyaanshC , and ArpitaSingh12 to this issue? They will be working with me on this. But only I will send in the pull request.

**Comment by prodigyinfotech** [comment]
Hey @ahaandesai27 please ask them to comment on the issue first

**Comment by ayush-bothra** [comment]
hello, I am ayush, as mentioned above, I will be contributing alongside ahaandesai27 on this project

**Comment by ArpitaSingh12** [comment]
Hello, I am Arpita as mentioned I will also be working on this issue along with @ahaandesai27 .

**Comment by ayush-bothra** [comment]
@prodigyinfotech , I wanted to clarify, are we supposed to build an image classifier (binary images) or a multi-class classifier using tabular features ( features part). the statement is a bit confusing
or are we required to do both?

**Comment by prodigyinfotech** [comment]
Hey @ayush-bothra you need to build Multi class classifier to identify plant species from binary leaf images

**Comment by ayush-bothra** [comment]
thanks

**Comment by ahaandesai27** [comment]
Can we use the pre-extracted features in the csv or directly images?

**Comment by prodigyinfotech** [comment]
It's up to you. But we would recommend to directly use images.

**Comment by ahaandesai27** [comment]
By when would you require the submission?

**Comment by prodigyinfotech** [comment]
By 28th October

**Comment by ahaandesai27** [comment]
Ok cool
