### ISSUE TITLE
Flower Recognition Model

### ISSUE THREAD

**Issue by Manavr472** [Prodigy-InfoTech/Machine-Learning-Projects#8]
### 🔖 Project description

Project Description:
Create a flower recognition system using Convolutional Neural Networks (CNNs) to classify five common flower types: Rose, Chamomile, Dandelion, Sunflower, and Tulip.

Key Objectives:
-Collect a diverse dataset of labeled flower images.
-Preprocess the data for model training.
-Design and train a CNN model for accurate classification.
-Validate and test the model's performance.
-Deploy a user-friendly web/mobile application for flower recognition.
-Document the project and provide a user guide.
-Ensure scalability and maintenance.

### 🎤 Pitch

Our project uses advanced Convolutional Neural Networks (CNNs) to classify five common flower types: Rose, Chamomile, Dandelion, Sunflower, and Tulip, instantly from photos. Whether you're a gardener, botanist, or just love flowers, our user-friendly app lets you snap a pic for accurate species identification, all while prioritizing ethics and scalability.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/Prodigy-InfoTech/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by prodigyinfotech** [comment]
Hey @Manavr472,  we have assigned you the issue.
You can start working on it.

**Comment by Manavr472** [comment]
Thank you
